# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md
# https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md

root: true

env:
  node: true

overrides:
  # Linter settings for JavaScript and TypeScript
  - files: [ "**/*.{js, jsx}" ]
    parserOptions:
      ecmaVersion: 2020
      ecmaFeatures:
        jsx: true
    env:
      es6: true
    extends:
      - eslint:recommended

  # Linter settings for TypeScript
  - files: [ "**/*.{ts, tsx}" ]
    parser: "@typescript-eslint/parser"
    parserOptions:
      ecmaVersion: 2020
      sourceType: module
      project: tsconfig.json
      ecmaFeatures:
        jsx: true
    plugins:
      - "@typescript-eslint"
      - "react"
      - "react-hooks"
      - "jsx-a11y"
    extends:
      - eslint:recommended
      - plugin:react/recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - plugin:jsx-a11y/recommended
      - plugin:import/errors # For catching immediately-executed imports e.g. - "import ./baz".
      - plugin:import/typescript # Disable rules that overlap with typescript.
      - plugin:prettier/recommended # Run prettier an an eslint rule that respects prettierrc. Integrates with eslint-config-prettier. Disable overlapping eslint rules.
      - prettier/@typescript-eslint # disable any overlapping typescript-eslint rules
    rules:
      no-case-declarations: warn
      "@typescript-eslint/ban-types": off
      "@typescript-eslint/ban-ts-comment": warn
      "@typescript-eslint/no-non-null-assertion": warn
      "@typescript-eslint/no-unsafe-member-access": warn
      "@typescript-eslint/no-unsafe-assignment": warn
      indent:
        - "error"
        - 2

