version: '3.6'

services:

  backend:
    image: kpcwebdev/learning_lynx-backend:latest
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - 1993:1993

  frontend:
    image: kpcwebdev/learning_lynx-frontend:dev
    env_file:
      - .env
    depends_on:
      - backend
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./Dockerfile

  db:
    image: postgres:12.3-alpine
    env_file:
      - .env
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:6.0.6
    env_file:
      - .env
    command: redis-server # --requirepass ${REDIS_SECRET}
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis-data:/var/lib/redis
      - ./docker/redis.conf:/user/local/etc/redis/redis.conf
    environment:
      REDIS_REPLICATION_MODE: master

  pgadmin:
    image: dpage/pgadmin4:4.23
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    ports:
      - 5050:5050
    environment:
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

  adminer:
    image: adminer:latest
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pappu687  # pepa-linha / lucas-sandery / pappu687

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
